### ISSUE TITLE
AMM 余额数据的bug。

### ISSUE THREAD

**Issue by dong77** [Loopring/loopring-web-v2#161]
<img width="326" alt="Screen Shot 2021-11-18 at 22 44 12" src="https://user-images.githubusercontent.com/1710087/142437284-7bdd4e74-392f-4766-be07-12e359259dd3.png">
<img width="858" alt="Screen Shot 2021-11-18 at 22 43 57" src="https://user-images.githubusercontent.com/1710087/142437367-2f95bd27-3387-487c-8900-2544f2027771.png">

**Comment by Jye924** [comment]
![image](https://user-images.githubusercontent.com/20452395/144035518-76f242c0-ef9a-4c21-b724-acb30ba2f03d.png)

2层资产的My AMM Liquidity列表中，后面显示的是赚取的池子交易手续费。
