### ISSUE TITLE
About guardians and Wallet Security Link Doesn't work

### ISSUE THREAD

**Issue by adam-bro** [Loopring/loopring-web-v2#213]
On https://security.loopring.io/ if you click on 'About guardians and Wallet Security', the page is blank
<img width="247" alt="Screen Shot 2021-12-02 at 11 16 25 AM" src="https://user-images.githubusercontent.com/84410897/144460478-19091e4d-7217-4960-ac6c-6ee50a606e87.png">

**Comment by SylvanasGone** [comment]
fixed in https://github.com/Loopring/hebaowebapp/pull/44
