### ISSUE TITLE
there's an UI bug that happens on firefox browsers. Lines on the chart are always not aligned with the cross hair, there's an offset

### ISSUE THREAD

**Issue by Jye924** [Loopring/loopring-web-v2#216]
![image](https://user-images.githubusercontent.com/20452395/144690461-e0463527-373a-4829-a271-f5c57596af02.png)

**Comment by brettwilcox** [comment]
It has something to do with this class.

```html
<rect width="664" height="320" style="opacity: 0;" class="react-financial-charts-crosshair-cursor"></rect>
```

**Comment by brettwilcox** [comment]
This is the project used for the chart - https://github.com/liihuu/KLineChart

https://github.com/Loopring/loopring-web-v2/blob/master/packages/component-lib/src/components/charts/scaleAreaChart/KlineChart/KlineChart.tsx

https://github.com/Loopring/loopring-web-v2/blob/master/packages/component-lib/src/components/charts/scaleAreaChart/KlineChart/KlineChart.stories.tsx

When I try to build the storybook, it's not working.

```bash
Error: You attempted to import /Users/aa815480/Dev/loopring-web-v2/node_modules/@storybook/theming/node_modules/@emotion/styled/base which falls outside of the project src/ directory. Relative imports outside of src/ are not supported.
You can either move it inside src/, or add a symlink to it from project's node_modules/.
[ESLintError:
src/components/tradePanel/Panel.stories.tsx
  Line 210:10:  'TransferPanell' is not defined  react/jsx-no-undef
  Line 213:14:  'TransferPanell' is not defined  react/jsx-no-undef
```
