### ISSUE TITLE
RFOX/ETH pool isn't showing fee rewards after 24 hours

### ISSUE THREAD

**Issue by adam-bro** [Loopring/loopring-web-v2#229]
A user on Discord was unable to see LP fees earned on the RFOX/ETH pool. He was only able to see the rewards on the UI once he withdrew it from the pool. I'm not sure if this issue is only related to this specific pool

https://discord.com/channels/488848270525857792/900801318078271508/917884077200265288
<img width="589" alt="Screen Shot 2021-12-08 at 3 34 38 PM" src="https://user-images.githubusercontent.com/84410897/145280469-712482da-b4a5-4d2d-9dd2-4f70d863762b.png">

**Comment by PeterHeng666** [comment]
The fee would not show until some one join or exit the pool now.

**Comment by windatang** [comment]
It's not issue
