### ISSUE TITLE
JS SDK才需要支持counterfactual NFT的几个新方法

### ISSUE THREAD

**Issue by dong77** [Loopring/loopring-web-v2#230]
1. ipfsHashToNftID(ipfsHash): 把一个IPFS hash转换成uint的NFTID
2. nftIDtoIpfsHash(nftID): 把一个uint的NFTID转换成IPFS hash

**Comment by windatang** [comment]
https://github.com/Loopring/loopring_sdk/issues/25
report it to SDK repo
