### ISSUE TITLE
Website/App not responsive to mobile device screen dimensions. 

### ISSUE THREAD

**Issue by puan0601** [Loopring/loopring-web-v2#236]
Difficult to use on Galaxy S21+ with MetaMask browser. Add a couple @media queries in the least, or make the whole app responsive?

**Comment by SylvanasGone** [comment]
@puan0601 Sorry for bad experience in our web app, we are now focusing on new features like layer2 NFT and something more. But we will definitely make it after Q4.
You can find better mobile expoerience in Loopring wallet for now. https://loopring.io/#/wallet

**Comment by puan0601** [comment]
Hi,

I am a front-end react developer as well. If I make a PR improving the
mobile layout, can I be compensated in LRC?

I've attached a screengrab of how bad the mobile layout is. I can't even
see how much LRC I have... it feels unusable to me in its current state on
mobile devices.
