### ISSUE TITLE
Can we add Smart Wallet Landing Page tab on loopring.org

### ISSUE THREAD

**Issue by adam-bro** [Loopring/loopring-web-v2#239]
<img width="545" alt="Screen Shot 2021-12-11 at 11 15 02 AM" src="https://user-images.githubusercontent.com/84410897/145683586-f9ca8e1e-4f75-4dba-9d02-381b42bfcee3.png">

There's no reference to the smart wallet on loopring.org. It will improve its visibility

**Comment by windatang** [comment]
smart wallet  introduce only on IO
