### ISSUE TITLE
Dev run script failing to compile 

### ISSUE THREAD

**Issue by itsbapic** [Loopring/loopring-web-v2#266]
Please let me know if I'm doing something incorrectly here, but it seems that the main ```npm run dev``` script to get the web app running locally returns the following error (this is after yarn install etc)

```
../component-lib/src/components/tableList/rewardTable/index.tsx 12:0      
Module parse failed: The keyword 'interface' is reserved (12:0)
File was processed with these loaders:
 * ../../node_modules/@pmmmwh/react-refresh-webpack-plugin/loader/index.js
You may need an additional loader to handle the result of these loaders.  
| import { TablePaddingX } from '../../styled'
|
> interface Row {
|     amount: string
|     time: number
```

Some research is showing that it could be a problem with Typescript and the monorepo lerna config? Please let me know if I'm doing something wrong here, or close if this is not an issue that can be duplicated elsewhere

**Comment by windatang** [comment]
yarn install

**Comment by itsbapic** [comment]
As previously mentioned @windatang, this occurs after running ```yarn install``` in the root directory. I manually ran ```cd ./packages/webapp``` then ```yarn dev``` which are contained in the ```npm run dev``` command, but am still getting the same error when attempting to start the development server. I have run the commands exactly how they are shown in the README.md, but persistently keep getting the same above error.
