### ISSUE TITLE
VIP Page using Safari Browser Continues Expanding to the Right

### ISSUE THREAD

**Issue by chrisdudek** [Loopring/loopring-web-v2#268]
When I navigate to https://loopring.io/#/layer2/vip using a Safari browser (Version 15.1), the two main sections continue expanding to the right until most of the text is off-screen. I do not have this issue when using Brave Browser.
![Screen Shot 2021-12-16 at 9 49 56 AM](https://user-images.githubusercontent.com/11835064/146403760-5c2d0d70-b881-4064-8a97-e0d9cea5d834.png)

**Comment by windatang** [comment]
Safari is support for all the feature, due to it have no plugin as metamask. not maintain it
