### ISSUE TITLE
Landing page show "TOTAL USER" and "NUMBER OF TRADES" prefixed by dollar sign.

### ISSUE THREAD

**Issue by chavalitp** [Loopring/loopring-web-v2#29]
Landing page show "TOTAL USER" and "NUMBER OF TRADES" prefixed by dollar sign.
![image](https://user-images.githubusercontent.com/7431348/137150585-fe88af81-e422-475e-8797-ec126dd8162b.png)

**Comment by SylvanasGone** [comment]
> Landing page show "TOTAL USER" and "NUMBER OF TRADES" prefixed by dollar sign. ![image](https://user-images.githubusercontent.com/7431348/137150585-fe88af81-e422-475e-8797-ec126dd8162b.png)

The next release(soon) will fix them, thanks for your report!
