### ISSUE TITLE
比赛停止公告将于明天公开。不和谐用户会在最后发现

### ISSUE THREAD

**Issue by TransientOddity** [Loopring/loopring-web-v2#296]
比赛停止公告将于明天公开。不和谐用户会在最后发现

**Comment by DurbanBourbon** [comment]
The announcement of the game suspension will be made public tomorrow. Discord users will find out at the end. Please comment @loopring. Being posted on discord as FUD. Need clarification.

**Comment by b-loopring** [comment]
Please don't spam our github - the above is not a Loopring contributor
