### ISSUE TITLE
Deposit ETH from L1 to L2 wallet fails due to invalid character

### ISSUE THREAD

**Issue by SiffKopp** [Loopring/loopring-web-v2#298]
Hi there,
I'm a new customer and tried to deposit some ETH to create my L2 wallet on loopring.io.

I always got a JS "invalid character" error while trying to deposit after entering the transfer amount.

I think it's a decimal seperator issue. I'm german and we use a "," for seperation.
After switching the browser language to english it worked just fine.
 
As you surely can expect some european customers, I guess this should be fixed. :)

![grafik](https://user-images.githubusercontent.com/46872968/146915679-c28eab7e-7d73-4042-9aa6-26eca267cd8d.png)

for context, my connected MetaMask wallet is:
0xf3535a00Ae196EB20A18Cdec29e725Ed91D0B105

UPDATE:
It seems like my wallet creation didn't work perfectly too, as there's a JS Error as transaction data.

Transaction:
https://etherscan.io/tx/0xdb8db5162be01a8cb91f8aa91d8576b3797bce6897c0f55c42f07f467993477b

![grafik](https://user-images.githubusercontent.com/46872968/146922104-94da4f0f-87a1-4467-8e0d-386af58d57e7.png)

If there's any further questions, feel free to contact me.

**Comment by windatang** [comment]
Please change your language to US, we will plan for that it already add into our backlog  we current not support for , as for seperation. 
& for productor issue please use https://desk.zoho.com/portal/loopring/en/home to report
