### ISSUE TITLE
WalletConnect display issue on mobile devices

### ISSUE THREAD

**Issue by odesium** [Loopring/loopring-web-v2#299]
When using a mobile device for visiting the loopring.io site and connecting the wallet using WalletConnect, users can swipe to the right on the screen where it says "Connect Wallet to WalletConnect“

You can see on each screen as you swipe - QR Code, Connecting, Success, Fail

https://user-images.githubusercontent.com/56487762/146925059-e33c801a-0c4c-4b8b-a231-67bb253673c6.MP4

**Comment by windatang** [comment]
not support for mobile, future plan dev mobile Dex
