### ISSUE TITLE
VIP Screen in L2 Wallet moves to the right

### ISSUE THREAD

**Issue by pikespeak** [Loopring/loopring-web-v2#309]
When i open L2 Wallet > VIP Menu, it turns the table automatically further and further to the right. it grows further and further

screenshot: https://imgur.com/a/7ziumF9

i am on Mac OS 12.1 and opend the wallet on Safari Version 15.2 (17612.3.6.1.6)

**Comment by chrisdudek** [comment]
I created the same issue earlier. Winda closed it out stating that since Safari does not support all of the features, i.e. MetaMask extension, they do not plan to support Safari. I would recommend using Brave (or Chrome).

**Comment by windatang** [comment]
safari is not our suggestion browe
