### ISSUE TITLE
account tag的使用方法

### ISSUE THREAD

**Issue by Jye924** [Loopring/loopring-web-v2#351]

**Comment by Jye924** [comment]
account的tags是以逗号分隔的，里面不只有vip，比如返回的结果可能是"vip_1,updatePaid",
客户端要使用vip的时候要以逗号分割去使用，找里面的vip相关项。

**Comment by windatang** [comment]
accInfo.tags?.split(";").find((item) => /vip/gi.test(item)) ?? "",
