### ISSUE TITLE
Same trade, Different Fees API vs. Website

### ISSUE THREAD

**Issue by adam-bro** [Loopring/loopring-web-v2#363]
This user would like to know why fees are .3% when using the API and .28% when using the website. Is the .3% - .28% difference related to API vs. loopring.io? Or could this be related to order routing AMM vs. Orderbook? Or possibly something else.
0x9c6Ea5FcFC8D3D144d037394188278d9Ec74dA23

<img width="823" alt="Screen Shot 2022-01-07 at 12 28 08 AM" src="https://user-images.githubusercontent.com/84410897/148496841-e9159f08-5c69-4cf8-aa2f-a5d1de038572.png">
<img width="817" alt="Screen Shot 2022-01-07 at 12 28 13 AM" src="https://user-images.githubusercontent.com/84410897/148496850-a2710428-5474-4020-9bc1-382b23a03fd4.png">

**Comment by windatang** [comment]
@PeterHeng666  v3 or v2？？？
