### ISSUE TITLE
浏览器语言为非英语时，修改挂单价格，下单量会显示NaN

### ISSUE THREAD

**Issue by Jye924** [Loopring/loopring-web-v2#366]
https://www.reddit.com/r/loopringorg/comments/rvwzti/the_comma_bug_that_keeps_europeans_from_trading/?utm_source=share&utm_medium=ios_app&utm_name=iossmf

**Comment by windatang** [comment]
, 号引起 的先忽略修不了

**Comment by boppbo** [comment]
@windatang That is an i18n issue - should be reopened. There are several regions that use "," as a valid decimal separator character. https://docs.microsoft.com/en-us/globalization/locale/currency-formatting
