### ISSUE TITLE
Suggestion - Hover Text Over Buttons

### ISSUE THREAD

**Issue by adam-bro** [Loopring/loopring-web-v2#372]
A lot of users are confused with some of our L2/crypto language, they don’t understand what some of the buttons mean on loopring.io

I think this can be easily simplified for the user by adding “onHover” functionality. It’s a really simple HTML/CSS fix that allows a user to see a pop out text box when they hover over each button with their mouse. I think the descriptions that pop out could be:

-Buy with Ramp - “Buy on L2 through Ramp”
-Transfer - “Transfer to another L2”
-Withdraw - “Withdraw to L1”
-Deposit - “Deposit funds from L1”

![hover-over-me](https://user-images.githubusercontent.com/84410897/149603515-606c14bb-7288-43d5-b036-2ccff7a749a8.png)
![withdraw](https://user-images.githubusercontent.com/84410897/149603516-14fff0aa-342e-4fee-a882-a70900ae9965.png)

**Comment by Rishi6229** [comment]
hey can I work on this issue?

**Comment by Rishabh32700** [comment]
i'am interested

**Comment by Rishabh32700** [comment]
hey i have fixed your issue
would you like to review

**Comment by Rishabh32700** [comment]
i have a solution and i am working on it

**Comment by Rishi6229** [comment]
Bro Rishabh you I'll mannered or something when you saw that already shown
interest first how come you too came into this issue ?

Find some other issue work upon it.

**Comment by Rishabh32700** [comment]
bro this is not your project everyone has right to contribute and no matter who came first it's upto the project owner to whom he give chance better keep your words with you.

**Comment by windatang** [comment]
![image](https://user-images.githubusercontent.com/1582816/150290728-d3fb91e3-ea23-4cab-82e8-e4aa2846b2b8.png)

**Comment by windatang** [comment]
at popup we already have the description
