### ISSUE TITLE
Order book component doesn't fill the height when resized

### ISSUE THREAD

**Issue by ioanwurf** [Loopring/loopring-web-v2#381]
Reposting from https://github.com/Loopring/dexwebapp/issues/264 for visibility

**Comment by windatang** [comment]
never ever support for that . you can drag it yourself

**Comment by ioanwurf** [comment]
I know I can manually force the widget to fill it the vertical space when refreshing the page (by dragging the bottom-right handle again). Is this the reason you closed the issue? I don't think this is a proper workaround, especially if you have to refresh the page a lot because of other issues.
