### ISSUE TITLE
Intermittent - New addresses not activating L2 on webapp after deposits but works on legacy

### ISSUE THREAD

**Issue by odesium** [Loopring/loopring-web-v2#393]
Occasionally users have issues with first deposits activating L2 on webapp but connecting to legacy.loopring.io website resolves the issues.
![image](https://user-images.githubusercontent.com/56487762/150523274-fe7ff512-4d80-4bbd-bd64-d2c77148871f.png)
![chrome_dnDU6s3o02](https://user-images.githubusercontent.com/56487762/150523499-6eb4ceb6-81d4-4765-b947-a045ea975368.png)
Address above not recognised on webapp for withdrawal but connecting to legacy.loopring.io was not an issue to withdraw. For most reports on Discord, after connecting to legacy site, loopring.io works.

![image](https://user-images.githubusercontent.com/56487762/150523872-ff53a1cf-ef80-401b-93d3-e56caba719a4.png)

**Comment by windatang** [comment]
It‘s may not an issue this adddres is CF addres it cannot withdraw

**Comment by odesium** [comment]
> It‘s may not an issue this adddres is CF addres it cannot withdraw

User was sending from a metamask address on PC L2 Dex to Withdraw from L2 to the Counterfactual wallet L1 to activate it but the address is not recognised.
