### ISSUE TITLE
Linking wrong NFTID loopring.io->Explorer

### ISSUE THREAD

**Issue by adam-bro** [Loopring/loopring-web-v2#523]
There is an issue with the linking back to explorer from loopring.io for some NFTs. The nft pictured has the nftId 0x85945aad4e3fbdbba9f2276d5e9019d2d7d15690348b0e9b53d50e0c2101df6  when it should really be 0x085945aad4e3fbdbba9f2276d5e9019d2d7d15690348b0e9b53d50e0c2101df6

The explorer link within the detailed view for it takes you to a page with the wrong nft id of 0x85945aad4e3fbdbba9f2276d5e9019d2d7d15690348b0e9b53d50e0c2101df6   -> https://explorer.loopring.io/nft/0x94b90c9b95ae5ff167fc16c4aa2b9857367729a0-0-0x7b0bf5b5baafa98138fd41a4b3592df17fc4e36f-0x85945aad4e3fbdbba9f2276d5e9019d2d7d15690348b0e9b53d50e0c2101df6-10    <- This just has endless loading

The link should take you to the page with the nft id of 0x085945aad4e3fbdbba9f2276d5e9019d2d7d15690348b0e9b53d50e0c2101df6    https://explorer.loopring.io/nft/0x94b90c9b95ae5ff167fc16c4aa2b9857367729a0-0-0x7b0bf5b5baafa98138fd41a4b3592df17fc4e36f-0x085945aad4e3fbdbba9f2276d5e9019d2d7d15690348b0e9b53d50e0c2101df6-10   <- This one loads

This is related to the original minting issue with the nft id not having 0x0 for some ids: https://github.com/Loopring/loopring_sdk/pull/52  I think loopring.io needs a similar fix for displaying. 

I also wonder if this could be one of the reasons for Unknown NFT in the mobile wallet too? 

![1](https://user-images.githubusercontent.com/84410897/170807825-94b96d29-b1cf-46a0-a5e1-743722997cbb.png)

https://github.com/Loopring/loopring_sdk/pull/52

Thanks Fudgey!

**Comment by PeterHeng666** [comment]
what's the logic of explorer to find the correct info by the link?
Actually, the nftId is a number just show in hex value, explorer need compare the number value but not the string to find the correct one.
Would you help to confirm with explorer logic?
