### ISSUE TITLE
NFT Minting Page Wording

### ISSUE THREAD

**Issue by adam-bro** [Loopring/loopring-web-v2#525]
Original: I confirm that the NFT minted does not infringe on copyright laws or contain illegal, explicit, sensitive, adult themed, or any other content considered NSFW. We reserve the right to delete NFTs or hide inappropriate content if an NFT is discovered to be harmful.

Change to: I confirm that the NFT minted does not infringe on copyright laws or contain illegal, explicit, sensitive, adult themed, or any other content considered NSFW. We reserve the right to hide inappropriate content if an NFT is discovered to be harmful.

<img width="434" alt="Screen Shot 2022-05-30 at 10 01 52 PM" src="https://user-images.githubusercontent.com/84410897/171078154-2f4bb607-0e5d-4ce9-a822-0652beaff96d.png">

**Comment by Jye924** [comment]
It has been fixed in the latest web version: VER: fbcd60a_prod
