### ISSUE TITLE
Metadata Issue using Simple 'Create NFT' (use "attributes" instead of "properties")

### ISSUE THREAD

**Issue by adam-bro** [Loopring/loopring-web-v2#530]
Please change:  "properties" to "attributes" and "key" to "trait_type".
-----
lexplorer.io and GME Wallet are having issues showing the Traits for NFTs minted using the "simple" Create NFT method. It looks like there are clear differences in the metadata when using Simple vs. Advanced - which makes sense since Advanced can contain anything the minter/creator wants to include.

working in lexplorer (used Advance Create): https://loopring.mypinata.cloud/ipfs/Qmcn8yRMXaMfXLvvavFbsntytxC4cu36qq9aKutDxESesc

not working in lexplorer (used Create NFT):
https://loopring.mypinata.cloud/ipfs/QmSAKXNq34XL6GGwh7s2cUBswt9G4vM3ywSExkbKMCZtwU

notice how the working has "attributes" and the not working has "properties". also, the not working is using a different naming convention (key vs. trait_type) 

looks like metadata standards are to use "trait_type": https://docs.opensea.io/docs/metadata-standards

https://github.com/Loopring/dexwebapp/issues/278

**Comment by itsgboccia** [comment]
![image](https://user-images.githubusercontent.com/103235752/171523529-aaf82c58-848f-4290-973d-287bb61b160f.png)
Here's an example of how it should look if you used either "attributes" or "properties" as the standard. I believe the Gamestop Marketplace standard is the properties array vs the attributes one (trait types).
