### ISSUE TITLE
The amount entered is automatically cleared in the receive panel

### ISSUE THREAD

**Issue by Jye924** [Loopring/loopring-web-v2#531]
https://user-images.githubusercontent.com/20452395/171561826-82ae30a9-d68d-47dc-a752-20413c6ab76d.mov

![Image](https://user-images.githubusercontent.com/20452395/171561883-5ca3366f-e91a-4964-af0b-410937205e47.png)

![Image](https://user-images.githubusercontent.com/20452395/171561913-51ef6b16-ed1d-4932-823b-5b6429ead32b.png)

**Comment by windatang** [comment]
现象的原因猜测
如果有一笔正在进行的自我转账就会有一个后台轮训。。再更新资产。。会把reset 和资产更新监听分开加个flag 保留原始填写数据应该就不会在发生了
测试网deposit 比较快所以不会产生这个现象
