### ISSUE TITLE
Mint NFT - advance create - CID input field delay

### ISSUE THREAD

**Issue by rosareth** [Loopring/loopring-web-v2#532]
When using Advance Create: (Tested using Chrome version 102.0.5005.63 (64-bit)):
1. the CID input field does not always show the CID pasted until after the NFT has been loaded from pinata. This is confusing and leads to trying to input several times.
2. Often it seems to be necessary to copy-paste the CID several times before the NFT is properly displayed.

**Comment by windatang** [comment]
it's dependent on your IPFT server router time, that's a correct case
