### ISSUE TITLE
Mint NFT - advance create - no approval screen appears on Android wallet

### ISSUE THREAD

**Issue by rosareth** [Loopring/loopring-web-v2#533]
When using Mint NFT - Advance Create:  (Tested using Chrome version 102.0.5005.63 64 bit and Android wallet on Samsung S10):

When connected using WalletConnect on Android, the session seems to be lost after a while. When you click "Mint NFT" and the pop-up is waiting for wallet approval, there is no action on the Android device (still shows the "Connected Successful" screen, but there is no Approval pop-up on the Android device).
Only work around I have found is to disconnect on the web page and then reconnect.

**Comment by windatang** [comment]
it's a right case... we will keep some use information on local variable
