### ISSUE TITLE
mini order for market and swap

### ISSUE THREAD

**Issue by windatang** [Loopring/loopring-web-v2#537]

**Comment by PeterHeng666** [comment]
add tradeCost return in api/v3/user/orderUserRateAmount.

1 calculate the maxFeeBips when place order(not smaller than tradeCost/amountB), maxFeeBips can not bigger than 5000(50%)
2 orderType can only be TAKER_ONLY or AMM (can not be MAKER_ONLY)
3 amountS(volume in sellToken) and amountB(volume in buyToken) can not smaller than minimum of orderAmounts in /api/v3/exchange/tokens

**Comment by windatang** [comment]
https://github.com/orgs/Loopring/projects/4/views/22
