### ISSUE TITLE
Show Full NFT ID on NFT page

### ISSUE THREAD

**Issue by adam-bro** [Loopring/loopring-web-v2#573]
can we please show the NFT ID in hex format 

<img width="445" alt="Screen Shot 2022-07-05 at 10 03 59 PM" src="https://user-images.githubusercontent.com/84410897/177451923-3bea5b75-0b04-4c1f-b172-67b4965b3d09.png">

**Comment by fudgebucket27** [comment]
Can it actually be shown in hexadecimal format? The official explorer shows the nft id in hex format and on my lexplorer site we have search enabled for the hexademical nft id.

**Comment by windatang** [comment]
Sorry for support more customer our product decide keep current formate
