### ISSUE TITLE
Advanced mint with GME wallet causes invalid explorer link from web wallet

### ISSUE THREAD

**Issue by Montspy** [Loopring/loopring-web-v2#575]
I used the advanced mint with a GME wallet and the explorer link from the web wallet ended up being invalid.

Here is the invalid link from wallet: https://explorer.loopring.io/nft/0x138F9286E39f45f493F89c221FBD1Ac50003D7A6-0-0x94989ba7b797cadcb119b2bc2b80b04ca858af89-0xac6e690430e9536a6ff8700749e37687b42694176bca24a972175fccedb38713-5

The valid link should have the `minterAddress` all in lower case like so:
https://explorer.loopring.io/nft/0x138f9286e39f45f493f89c221fbd1ac50003d7a6-0-0x94989ba7b797cadcb119b2bc2b80b04ca858af89-0xac6e690430e9536a6ff8700749e37687b42694176bca24a972175fccedb38713-5

I believe this is caused by the GME wallet returning the account address with **some upper case** `0x138F9286E39f45f493F89c221FBD1Ac50003D7A6` when the webapp is expecting **all lower case** `0x138f9286e39f45f493f89c221fbd1ac50003d7a6`

I console.log this line https://github.com/Loopring/loopring-web-v2/blob/released/packages/core/src/hooks/useractions/useNFTMintAdvance.ts#L493
With MetaMask wallet:
```js
{
accAddress: "0x1c65331556cff08bb06c56fbb68fb0d1d2194f8a"
​accountId: 34247
​apiKey: "yyyyyyyyyyyyyyyyyyyyyyyyyyy"
}
```

With GME wallet:
```js
{
accAddress: "0x138F9286E39f45f493F89c221FBD1Ac50003D7A6"
accountId: 134772
apiKey: "xxxxxxxxxxxxxxxxxxxxxxxxxxxxx"
}
```

As you can see the GME wallet has `accAddress` with some upper case. That causes the GraphQL request to return no result

The simple fix would be to lower case the account address returned by the GME wallet.

**Comment by windatang** [comment]
@adam-bro  please make sure explore url is Uncertainty of capitalization

**Comment by windatang** [comment]
will fix
