### ISSUE TITLE
Cannot send any or transfer to another L2 when connected to Loopring.io

### ISSUE THREAD

**Issue by Jye924** [Loopring/loopring-web-v2#583]
![Image](https://user-images.githubusercontent.com/20452395/181409448-3e821008-6059-49d5-aee1-cb2738fc9dd7.png)

The user has already deposited 40 to his L2 address here 0xc6422aEC4FEEfC40eAE3f4D9c6f55E4702058AAb. This is a metamask address but when connected to Loopring.io he cannot send any or transfer to another L2.

![Image](https://user-images.githubusercontent.com/20452395/181409686-a09e152b-3711-4fd0-9ab8-07d6be15be0f.png)

**Comment by windatang** [comment]
No reproduce

**Comment by windatang** [comment]
did you check the NFT is locked or unloced

**Comment by odesium** [comment]
@windatang here is a video from another user who has the same issue https://imgur.com/ECk4UkS
