### ISSUE TITLE
Loopring.io wording change

### ISSUE THREAD

**Issue by adam-bro** [Loopring/loopring-web-v2#740]
Please change "Cheap" to "100x Lower Fees"
It should read "Fast, Secure, and 100x Lower Fees"
<img width="1119" alt="Screen Shot 2023-07-03 at 11 02 53 AM" src="https://github.com/Loopring/loopring-web-v2/assets/84410897/966849a6-1e58-4377-bcfd-89e2b0a4cd38">

**Comment by windatang** [comment]
next release
