### ISSUE TITLE
Loopring.org word changes

### ISSUE THREAD

**Issue by adam-bro** [Loopring/loopring-web-v2#742]
Change: "Fast, secure and 100x lower fees, only on L2"
To: "Fast, Secure and 100x Lower Fees"

![Screen Shot 2023-07-03 at 12 59 20 PM](https://github.com/Loopring/loopring-web-v2/assets/84410897/dfceafe4-cf1b-49b5-af30-3944f98f2c1a)

**Comment by windatang** [comment]
https://github.com/Loopring/website/pull/232/files
